# Generated by Django 5.1.2 on 2025-03-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks_details", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="symbol",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
